# Generated by Django 4.0 on 2022-08-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dergiler',
            name='dergi_kapak',
            field=models.FileField(default='Default', upload_to='', verbose_name='Dergi Kapak'),
        ),
        migrations.AlterField(
            model_name='dergiler',
            name='dergi_pdf',
            field=models.FileField(default='Default', upload_to='', verbose_name='Dergi Dosya Pdf'),
        ),
    ]
