# Generated by Django 4.1 on 2022-08-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infos", "0002_alter_dergiler_dergi_kapak_alter_dergiler_dergi_pdf"),
    ]

    operations = [
        migrations.CreateModel(
            name="Small_Slider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "isim",
                    models.CharField(
                        default="İsim Gir", max_length=100, verbose_name="İsim"
                    ),
                ),
                (
                    "slider_image",
                    models.FileField(
                        blank=True,
                        default="Default",
                        null=True,
                        upload_to="",
                        verbose_name="Küçük Resim Ekle",
                    ),
                ),
            ],
        ),
    ]
