# Generated by Django 4.0 on 2022-08-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0003_small_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renkler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Aga bundan bir tane oluşturacaksınız', max_length=150, verbose_name='Aga bundan bir tane oluşturacaksınız')),
                ('contents', models.TextField(default='İçerik', verbose_name='Görevi')),
            ],
        ),
        migrations.AlterField(
            model_name='slider',
            name='isim',
            field=models.CharField(default='Minimum en az iki tane slider girin', max_length=100, verbose_name='Minimum en az iki tane slider girin'),
        ),
        migrations.AlterField(
            model_name='small_slider',
            name='isim',
            field=models.CharField(default='Minimum en az iki tane slider girin', max_length=100, verbose_name='Minimum en az iki tane slider girin'),
        ),
    ]
