# Generated by Django 4.0 on 2022-08-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0004_renkler_alter_slider_isim_alter_small_slider_isim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renkler',
            name='contents',
        ),
        migrations.AddField(
            model_name='renkler',
            name='Hakkımızda',
            field=models.TextField(default='Aga bundan bir tane oluşturacaksınız', verbose_name='Hakkımızda Renk'),
        ),
        migrations.AddField(
            model_name='renkler',
            name='Navbar',
            field=models.TextField(default='Aga bundan bir tane oluşturacaksınız', verbose_name='Navbar Renk'),
        ),
        migrations.AddField(
            model_name='renkler',
            name='Sayılar',
            field=models.TextField(default='Aga bundan bir tane oluşturacaksınız', verbose_name='Sayılar Renk'),
        ),
        migrations.AddField(
            model_name='renkler',
            name='Yazarlar',
            field=models.TextField(default='Aga bundan bir tane oluşturacaksınız', verbose_name='Yazarlar Renk'),
        ),
        migrations.AddField(
            model_name='renkler',
            name='copyright',
            field=models.TextField(default='Aga bundan bir tane oluşturacaksınız', verbose_name='copyright Renk'),
        ),
    ]
