# Generated by Django 4.1 on 2022-08-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infos", "0006_alter_renkler_hakkımızda_alter_renkler_navbar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="renkler",
            name="font",
            field=models.TextField(
                default="Arial, Helvetica, sans-serif", verbose_name="Title Font"
            ),
        ),
    ]
