# Generated by Django 3.2.15 on 2022-09-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0007_renkler_font'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(default='Logo Giriniz: ', max_length=100, verbose_name='İsim')),
                ('logo_image', models.FileField(blank=True, default='Default', null=True, upload_to='', verbose_name='Resim Ekle')),
            ],
        ),
        migrations.AlterField(
            model_name='slider',
            name='isim',
            field=models.CharField(default='Minimum en az iki tane slider girin', max_length=100, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='small_slider',
            name='isim',
            field=models.CharField(default='Minimum en az iki tane slider girin', max_length=100, verbose_name='İsim'),
        ),
    ]
