# Generated by Django 4.0 on 2022-09-24 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0008_auto_20220905_1222'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hakkımızda',
            new_name='Hakkimizda',
        ),
        migrations.RenameField(
            model_name='renkler',
            old_name='Hakkımızda',
            new_name='Hakkimizda',
        ),
    ]
