# Generated by Django 4.0 on 2022-09-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0009_rename_hakkımızda_hakkimizda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='renkler',
            name='Slider_arka_plan',
            field=models.TextField(default='#E2F4E0', verbose_name='Slider_arka_plan Renk'),
        ),
    ]
