# Generated by Django 4.0 on 2022-09-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0010_renkler_slider_arka_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='hakkimizda',
            name='slider_image',
            field=models.FileField(blank=True, default='Default', null=True, upload_to='', verbose_name='Hakkımızda Resim'),
        ),
    ]
