# Generated by Django 4.0 on 2022-09-29 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0011_hakkimizda_slider_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hakkimizda',
            old_name='slider_image',
            new_name='image',
        ),
    ]
