# Generated by Django 4.0 on 2022-10-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0012_rename_slider_image_hakkimizda_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='slider_link',
            field=models.CharField(default='link girin', max_length=1000, verbose_name='Slider Link'),
        ),
    ]
