# Generated by Django 4.0 on 2022-10-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0013_slider_slider_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='slider_link',
            field=models.CharField(default='link girin', max_length=1000, verbose_name='verilecek linki çift tırnak içinde yazın'),
        ),
    ]
